service: teste-kxc

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements: 
    - Effect: "Allow"        
      Action:
        - bedrock:InvokeModel      
        - bedrock:InvokeModelWithResponseStream      
      Resource: 
        - "*"

functions:
  ai-stream:
    handler: handler.handler
    timeout: 30
    url:
      invokeMode: RESPONSE_STREAM
  ai:
    handler: handler.handler2
    timeout: 30
    url: true